In [186]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [114]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\anaconda\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\anaconda\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
data = pd.read_excel(r"C:\Users\sarvesh jathar\Downloads\PAN+Card+Validation+in+PYTHON+-+Scripts\PAN Card Validation in PYTHON - Scripts\PAN Number Validation Dataset.xlsx")
data.head()

In [ ]:
total_records = len(data)

In [118]:
print(f'The dataset has {data.shape[0]} rows and {data.shape[1]} row')

The dataset has 10000 rows and 1 row

In [120]:
data['Pan_Numbers'] = data['Pan_Numbers'].astype('string')

In [122]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pan_Numbers  9035 non-null   string
dtypes: string(1)
memory usage: 78.3 KB

In [124]:
data['Pan_Numbers'] = data['Pan_Numbers'].astype('string').str.strip().str.upper()

In [126]:
data.head()

  Pan_Numbers
0  VGLOD3180G
1  PHOXD7232L
2  MGEPH6532A
3  JJCHK4574O
4  XTQIJ2330L

In [128]:
data[data['Pan_Numbers'] == '']

     Pan_Numbers
5019
5020

In [130]:
data.isnull().sum()

Pan_Numbers    965
dtype: int64

In [132]:
data = data.replace({'Pan_Numbers' : ''}, pd.NA)

In [134]:
data = data.dropna()

In [136]:
data.shape

(9033, 1)

In [138]:
data.duplicated().sum()

8

In [140]:
data['Pan_Numbers'].nunique()

9025

In [142]:
data.drop_duplicates(inplace = True)

In [144]:
data.shape

(9025, 1)

In [162]:
def has_adjacent_repitition(pan):
    # for i in range(len(pan)-1):
    #     if pan[i] == pan[i+1]:
    #         return True
    # return False
    return any(pan[i] == pan[i+1] for i in range(len(pan)-1))

print(has_adjacent_repitition('ABCDE'))
print(has_adjacent_repitition('AABCD'))

False
True

In [164]:
def is_sequential(pan):
    # for i in range(len(pan)-1):
    #     if ord(pan[i+1]) - ord(pan[i]) !=1:
    #         return False
    # return True
    return all(ord(pan[i+1]) - ord(pan[i]) == 1 for i in range(len(pan)-1))

print(is_sequential('ABCDO'))
print(is_sequential('MNOPQ'))
print(is_sequential('AAAAA'))

False
True
False

In [166]:
import re

In [178]:
def is_pan_valid(pan):
    if len(pan) != 10:
        return False

    if not re.match(r'^[A-Z]{5}[0-9]{4}[A-Z]$', pan):
        return False

    if has_adjacent_repitition(pan):
        return False

    if is_sequential(pan):
        return False
    return True

In [180]:
data['Status'] = data["Pan_Numbers"].apply(
    lambda x: "Valid" if is_pan_valid(x) else "Invalid"
)

In [182]:
data.head()

  Pan_Numbers   Status
0  VGLOD3180G    Valid
1  PHOXD7232L    Valid
2  MGEPH6532A    Valid
3  JJCHK4574O  Invalid
4  XTQIJ2330L  Invalid

In [184]:
data['Status'].unique()

array(['Valid', 'Invalid'], dtype=object)